param(
  [string]$Repo = 'C:\Users\GSENR\Desktop\gs-shift-log'
)

$ErrorActionPreference = 'Stop'
Set-Location $Repo

$Agent =
  Join-Path $Repo 'local-tools\ois-agent\ois-login.js'

$Node =
  'C:\Program Files\nodejs\node.exe'

if (-not (Test-Path -LiteralPath $Agent)) {
  throw "Agent file not found: $Agent"
}

if (-not (Test-Path -LiteralPath $Node)) {
  throw "Node.exe not found: $Node"
}

function Get-NewLine {
  param([string]$Text)

  if ($Text.Contains("`r`n")) {
    return "`r`n"
  }

  return "`n"
}

function Convert-NewLine {
  param(
    [string]$Text,
    [string]$NewLine
  )

  return $Text
    .Replace("`r`n", "`n")
    .Replace("`r", "`n")
    .Replace("`n", $NewLine)
}

Write-Host '===== Phase 3.0 Water AJAX trace ====='

Write-Host ''
Write-Host '===== Pre-patch syntax check ====='

& $Node --check $Agent

if ($LASTEXITCODE -ne 0) {
  throw 'Agent already has a syntax error before patch.'
}

$Text =
  [IO.File]::ReadAllText($Agent)

if ($Text.Contains('[PHASE3.0 WATER AJAX TRACE]')) {
  throw 'Phase 3.0 Water AJAX trace is already applied.'
}

foreach (
  $RequiredMarker in @(
    '[PHASE2.5 DIRECT V5] Limestone API complete',
    '[PHASE2.5 DIRECT V5] Gear/Pinion API complete',
    '[PHASE2.6 WARMUP]',
    '[PHASE2.7A WATER-EXCEL GATE]',
    '[PHASE2.7B ORGANIC OPTIONAL V2]',
    '[PHASE2.8B WATER-FIRST]'
  )
) {
  if (-not $Text.Contains($RequiredMarker)) {
    throw "Required previous phase marker is missing: $RequiredMarker"
  }
}

$Stamp =
  Get-Date -Format 'yyyyMMdd-HHmmss'

$Backup =
  "$Agent.before-phase30-water-trace-$Stamp.bak"

Copy-Item `
  -LiteralPath $Agent `
  -Destination $Backup `
  -Force

Write-Host "Backup: $Backup"

$Nl =
  Get-NewLine $Text

try {
  $CollectFunctionNeedle =
    'async function collectOisWaterTreatmentValues('

  $CollectFunctionIndex =
    $Text.IndexOf(
      $CollectFunctionNeedle
    )

  if ($CollectFunctionIndex -lt 0) {
    throw 'collectOisWaterTreatmentValues function was not found.'
  }

  $Helper =
    Convert-NewLine `
      -NewLine $Nl `
      -Text @'
/* =========================================================
  [PHASE3.0 WATER AJAX TRACE]

  Temporary diagnostic only.
  Captures POST /ajax/data traffic generated by one Water query.

  Logged:
  - command
  - tossdata/select payload
  - HTTP status
  - JSON result count / first rows

  No cookies, authorization headers, passwords, or session values
  are logged.
========================================================= */
function createPhase30WaterAjaxTrace(
  page,
  targetDate
) {
  const pendingResponses =
    new Set();


  const getRequestInfo =
    request => {
      const postData =
        String(
          request.postData() ||
          ""
        );


      const parameters =
        new URLSearchParams(
          postData
        );


      return {
        command:
          parameters.get(
            "cmd"
          ) ||
          parameters.get(
            "CMD"
          ) ||
          "",

        tossdata:
          parameters.get(
            "tossdata"
          ) ||
          parameters.get(
            "TOSSDATA"
          ) ||
          ""
      };
    };


  const isTargetRequest =
    request => {
      return (
        String(
          request.method() ||
          ""
        ).toUpperCase() ===
          "POST" &&
        String(
          request.url() ||
          ""
        ).includes(
          "/ajax/data"
        )
      );
    };


  const compactText =
    (
      value,
      limit =
        8000
    ) => {
      const text =
        String(
          value ??
          ""
        )
          .replace(
            /\s+/g,
            " "
          )
          .trim();


      return text.length >
        limit
        ? (
            text.slice(
              0,
              limit
            ) +
            "...[TRUNCATED]"
          )
        : text;
    };


  const summarizeResponse =
    responseText => {
      const normalized =
        String(
          responseText ||
          ""
        ).trim();


      if (
        !normalized
      ) {
        return {
          format:
            "empty"
        };
      }


      try {
        const parsed =
          JSON.parse(
            normalized
          );


        const result =
          parsed?.result;


        return {
          format:
            "json",

          keys:
            parsed &&
            typeof parsed ===
              "object"
              ? Object.keys(
                  parsed
                )
              : [],

          resultCount:
            Array.isArray(
              result
            )
              ? result.length
              : null,

          resultPreview:
            Array.isArray(
              result
            )
              ? result.slice(
                  0,
                  6
                )
              : result
        };

      } catch {
        return {
          format:
            "text",

          preview:
            compactText(
              normalized,
              4000
            )
        };
      }
    };


  const handleRequest =
    request => {
      if (
        !isTargetRequest(
          request
        )
      ) {
        return;
      }


      const {
        command,
        tossdata
      } =
        getRequestInfo(
          request
        );


      console.log(
        "[PHASE3.0 WATER AJAX TRACE] REQUEST " +
        JSON.stringify({
          targetDate,
          command,
          tossdata:
            compactText(
              tossdata,
              8000
            )
        })
      );
    };


  const handleResponse =
    response => {
      const request =
        response.request();


      if (
        !isTargetRequest(
          request
        )
      ) {
        return;
      }


      const task =
        (
          async () => {
            const {
              command,
              tossdata
            } =
              getRequestInfo(
                request
              );


            const responseText =
              await response
                .text()
                .catch(
                  error => {
                    return (
                      "[response read error] " +
                      (
                        error instanceof
                          Error
                          ? error.message
                          : String(
                              error ||
                              ""
                            )
                      )
                    );
                  }
                );


            console.log(
              "[PHASE3.0 WATER AJAX TRACE] RESPONSE " +
              JSON.stringify({
                targetDate,
                command,
                tossdata:
                  compactText(
                    tossdata,
                    8000
                  ),
                status:
                  response.status(),
                summary:
                  summarizeResponse(
                    responseText
                  )
              })
            );
          }
        )();


      pendingResponses.add(
        task
      );


      task.finally(
        () => {
          pendingResponses.delete(
            task
          );
        }
      );
    };


  return {
    start() {
      page.on(
        "request",
        handleRequest
      );


      page.on(
        "response",
        handleResponse
      );


      console.log(
        `[PHASE3.0 WATER AJAX TRACE] START ${targetDate}`
      );
    },


    async stop() {
      page.off(
        "request",
        handleRequest
      );


      page.off(
        "response",
        handleResponse
      );


      if (
        pendingResponses.size >
          0
      ) {
        await Promise.allSettled(
          [
            ...pendingResponses
          ]
        );
      }


      console.log(
        `[PHASE3.0 WATER AJAX TRACE] STOP ${targetDate}`
      );
    }
  };
}


'@

  $Text =
    $Text.Insert(
      $CollectFunctionIndex,
      $Helper
    )

  $CollectFunctionIndex =
    $Text.IndexOf(
      $CollectFunctionNeedle
    )

  if ($CollectFunctionIndex -lt 0) {
    throw 'collectOisWaterTreatmentValues could not be re-located.'
  }

  $CollectOnceStart =
    $Text.IndexOf(
      '  const collectOnce =',
      $CollectFunctionIndex
    )

  $CollectOnceEndNeedle =
    '  let result;'

  $CollectOnceEnd =
    $Text.IndexOf(
      $CollectOnceEndNeedle,
      $CollectOnceStart
    )

  if (
    $CollectOnceStart -lt 0 -or
    $CollectOnceEnd -lt 0
  ) {
    throw 'collectOnce block was not found.'
  }

  $OldCollectOnce =
    $Text.Substring(
      $CollectOnceStart,
      $CollectOnceEnd -
        $CollectOnceStart
    )

  $ExpectedNeedles =
    @(
      'await ensureOisAgentLoggedIn(',
      'await setOisEnvironmentDate(',
      'await clickOisEnvironmentRecalculateButton(',
      'return await waitForOisWaterTreatmentValues('
    )

  foreach ($Needle in $ExpectedNeedles) {
    if (-not $OldCollectOnce.Contains($Needle)) {
      throw "collectOnce is missing expected code: $Needle"
    }
  }

  $NewCollectOnce =
    Convert-NewLine `
      -NewLine $Nl `
      -Text @'
  const collectOnce =
    async () => {
      const phase30Trace =
        createPhase30WaterAjaxTrace(
          page,
          targetDate
        );


      phase30Trace.start();


      try {
        await ensureOisAgentLoggedIn(
          page,
          config
        );


        await setOisEnvironmentDate(
          page,
          targetDate
        );


        await clickOisEnvironmentRecalculateButton(
          page
        );


        return await waitForOisWaterTreatmentValues(
          page,
          targetDate
        );

      } finally {
        await phase30Trace.stop();
      }
    };


'@

  $Text =
    $Text.Substring(
      0,
      $CollectOnceStart
    ) +
    $NewCollectOnce +
    $Text.Substring(
      $CollectOnceEnd
    )

  [IO.File]::WriteAllText(
    $Agent,
    $Text,
    (New-Object Text.UTF8Encoding($false))
  )

  Write-Host ''
  Write-Host '===== Node syntax check ====='

  & $Node --check $Agent

  if ($LASTEXITCODE -ne 0) {
    throw 'Agent Node syntax check failed.'
  }

  Write-Host ''
  Write-Host '===== git diff --check ====='

  git diff --check -- `
    local-tools/ois-agent/ois-login.js

  if ($LASTEXITCODE -ne 0) {
    throw 'git diff --check failed.'
  }

  $Final =
    [IO.File]::ReadAllText($Agent)

  $Checks =
    [ordered]@{
      'Phase 3.0 marker' =
        $Final.Contains(
          '[PHASE3.0 WATER AJAX TRACE]'
        )

      'Request trace log' =
        $Final.Contains(
          '[PHASE3.0 WATER AJAX TRACE] REQUEST'
        )

      'Response trace log' =
        $Final.Contains(
          '[PHASE3.0 WATER AJAX TRACE] RESPONSE'
        )

      'Limestone direct kept' =
        $Final.Contains(
          '[PHASE2.5 DIRECT V5] Limestone API complete'
        )

      'Gear direct kept' =
        $Final.Contains(
          '[PHASE2.5 DIRECT V5] Gear/Pinion API complete'
        )

      'Phase 2.8B kept' =
        $Final.Contains(
          '[PHASE2.8B WATER-FIRST]'
        )

      'Organic optional kept' =
        $Final.Contains(
          '[PHASE2.7B ORGANIC OPTIONAL V2]'
        )
    }

  Write-Host ''
  Write-Host '===== Verification ====='

  foreach ($Entry in $Checks.GetEnumerator()) {
    Write-Host (
      $Entry.Key +
      ': ' +
      $Entry.Value
    )
  }

  if (
    $Checks.Values -contains
      $false
  ) {
    throw 'One or more verification checks failed.'
  }

  Write-Host ''
  Write-Host '===== Changed file ====='

  git status --short -- `
    local-tools/ois-agent/ois-login.js

  Write-Host ''
  Write-Host '===== Diff summary ====='

  git diff --stat -- `
    local-tools/ois-agent/ois-login.js

  Write-Host ''
  Write-Host '===== Phase 3.0 patch complete ====='
  Write-Host 'Water AJAX tracing is enabled only while a Water request is being processed.'
  Write-Host 'No credentials, cookies, or authorization headers are logged.'
  Write-Host 'Agent has NOT been restarted.'
  Write-Host 'Nothing has been staged or committed.'
}
catch {
  Write-Host ''
  Write-Host '===== Patch failed; restoring Agent ====='

  Copy-Item `
    -LiteralPath $Backup `
    -Destination $Agent `
    -Force

  Write-Host 'Restore complete.'

  throw
}
