import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
const root=path.resolve(process.argv[2]||process.cwd());
const source=fs.readFileSync(path.join(root,'maintenance/blower-history.js'),'utf8');
const html=fs.readFileSync(path.join(root,'maintenance/blower-history.html'),'utf8');
const tags=['104ETH03AN601','104ETH03AN602','104ETG30AN601','104ETG30AN602','204ETG30AN601','204ETG30AN602','104SDF01AN001','104SDF01AN002','204SDF01AN001','204SDF01AN002','204LMDF01AN001', "104HHL60AP611", "104HHL60AP621", "104HHL60AP631", "204HHL60AP611", "204HHL60AP621", "204HHL60AP631", "104HHL10AN611", "104HHL10AN621", "104HHL10AN631", "204HHL10AN611", "204HHL10AN621", "204HHL10AN631"];
const fixed='GSPOGE.ABB_DCS.003ETH03AN602XB04';
const signal='GSPOGE.ABB_DCS.TEST_CONFIRMED_BINARY_01'; // Test-only, never a production mapping.
function element(){return {value:'',textContent:'',innerHTML:'',hidden:false,checked:false,disabled:false,dataset:{},classList:{toggle(){},add(){},remove(){}},setAttribute(){},removeAttribute(){},replaceChildren(){},focus(){},showModal(){this.open=true;},close(){this.open=false;}};}
function harness({mobile=false,canWrite=true}={}){
 const nodes=new Map(),calls=[],statuses=[];
 const c=vm.createContext({console,localStorage:{getItem:()=>null},clearTimeout(){},document:{readyState:'loading',addEventListener(){},getElementById(id){if(!nodes.has(id))nodes.set(id,element());return nodes.get(id);}},window:{matchMedia:()=>({matches:mobile}),setTimeout(fn){fn();return 1;}}});
 const marker='  if (document.readyState === "loading") {';
 const expose='globalThis.ui={state,elements,cacheElements,renderAssetCard,openDataParcRuntimeDialog,submitDataParcRuntimeRange,syncDataParcBlowerRuntime,savedDataParcRunSignal,isDataParcRuntimeAsset}; globalThis.hooks=h=>{apiRequest=h.api;loadData=async()=>{};renderAssets=()=>{};showToast=()=>{};setDataparcRuntimeStatus=h.status;waitForMilliseconds=async()=>{};};\n';
 assert.equal(source.split(marker).length,2);vm.runInContext(source.replace(marker,expose+marker),c);
 const ui=c.ui;ui.cacheElements();ui.state.data={permissions:{canWrite},user:canWrite?{name:'Test'}:null,backfill:{hasRun:true,status:'complete'},assets:[],events:[]};
 let polled=0;c.hooks({api:async o=>{calls.push(JSON.parse(JSON.stringify(o)));if(o.body?.action==='create_blower_runtime_probe')return {item:{id:'request-test'}};if(o.method==='GET'){if(polled++===0)throw Object.assign(new Error('transient'),{status:503});return {items:[{id:'request-test',status:'complete'}]};}return {ok:true};},status:(...a)=>statuses.push(a)});return {ui,calls,statuses};
}
function asset(tag,extra={}){return {tagNumber:tag,blowerType:tag.includes('ETH')?'flyash_silo':tag.includes('ETG')?'flyash_bag':'organic_fuel',unitNo:'2',positionLabel:'#A',displayName:'Test Blower',lastReplacementAt:'2026-05-03T15:00:00.000Z',cycleStartState:'legacy',cycleStartRevision:'r1',cycleRuntimeRevision:'r2',cycleElapsedHours:1262.975,cycleRuntimeTracked:true,isRunning:true,severity:'unset',...extra};}
function register(ui,a){ui.state.data.assets=[a];ui.state.data.events=[{id:'replace',tagNumber:a.tagNumber,blowerType:a.blowerType,eventType:'replacement',eventDate:a.lastReplacementAt,sourceType:'manual',note:'Confirmed replacement'}];}

test('all twenty-three cards hide period lookup while retaining verified mapping helpers',()=>{const {ui}=harness();for(const tag of tags){const a=asset(tag);register(ui,a);assert.doesNotMatch(ui.renderAssetCard(a,{}),/data-asset-action="dataparc_runtime_probe"/);assert.equal(ui.savedDataParcRunSignal(a),tag===tags[1]?fixed:'');}assert.equal(ui.isDataParcRuntimeAsset(asset('104HHL60AP611')),true);});
test('one header status and a separate compact lookup row preserve running, stopped and unknown states',()=>{const {ui}=harness();for(const [extra,state,label] of [[{},'running','기동중'],[{isRunning:false},'stopped','정지중'],[{isRunning:false,operationState:'unknown'},'unknown','상태 미확인'],[{isRunning:false,cycleStartState:'pending'},'startup_pending','기동 대기']]){const a=asset(tags[0],extra);register(ui,a);const card=ui.renderAssetCard(a,{}),head=card.split('<div class="asset-status-group">')[1].split('</div>')[0];assert.equal((head.match(/operation-pill/g)||[]).length,1);assert.doesNotMatch(head,/기준 미설정|dataparc-runtime-action/);assert.match(card,new RegExp(`data-operation-state="${state}"`));assert.match(head,new RegExp(label));assert.doesNotMatch(card,/class="dataparc-runtime-row"/);}});
test('first lookup asks for a confirmed signal; saved sources prefill and B remains fixed',()=>{const {ui}=harness();const a=asset(tags[0]);register(ui,a);ui.openDataParcRuntimeDialog(a.tagNumber);assert.equal(ui.elements.dataparcRuntimeSourceTag.value,'');assert.equal(ui.elements.dataparcRuntimeConfirmSignal.checked,false);assert.equal(ui.elements.dataparcRuntimeSourceSettings.open,true);a.dataParcTag=signal;ui.openDataParcRuntimeDialog(a.tagNumber);assert.equal(ui.elements.dataparcRuntimeSourceTag.value,signal);assert.equal(ui.elements.dataparcRuntimeConfirmSignal.checked,true);assert.equal(ui.elements.dataparcRuntimeSourceSettings.open,false);const b=asset(tags[1]);register(ui,b);ui.openDataParcRuntimeDialog(b.tagNumber);assert.equal(ui.elements.dataparcRuntimeSourceTag.value,fixed);assert.equal(ui.elements.dataparcRuntimeSourceTag.readOnly,true);});
test('each asset creates once, retries GET on its own card, and applies by request ID only',async()=>{for(const tag of tags){const {ui,calls,statuses}=harness();await ui.syncDataParcBlowerRuntime(tag,'2026-05-09T15:00:00.000Z',{dataParcTag:signal,confirmRunSignal:true});const writes=calls.filter(c=>c.method==='POST');assert.equal(writes.length,2);assert.deepEqual(writes[1].body,{action:'dataparc_runtime_sync',requestId:'request-test'});if(tag===tags[1])assert.deepEqual(writes[0].body,{action:'create_blower_runtime_probe',startAt:'2026-05-09T15:00:00.000Z'});else{assert.equal(writes[0].body.assetTag,tag);assert.equal(writes[0].body.dataParcTag,signal);assert.equal(writes[0].body.confirmRunSignal,true);}assert.ok(statuses.some(s=>s[1]==='재연결 중'));assert.ok(statuses.every(s=>s[0]===tag));}});
test('missing, unconfirmed, malformed or wrong known signals never create a queue request',async()=>{for(const options of [{},{dataParcTag:signal},{dataParcTag:'204LMDF01AN001',confirmRunSignal:true},{dataParcTag:'GSPOGE.ABB_DCS.BAD"FORMULA',confirmRunSignal:true},{dataParcTag:'GSPOGE.ABB_DCS.BAD/TAG',confirmRunSignal:true},{dataParcTag:fixed,confirmRunSignal:true}]){const {ui,calls}=harness();await ui.syncDataParcBlowerRuntime(tags[0],'2026-05-09T15:00:00.000Z',options);assert.equal(calls.length,0);}});
test('real dialog keeps setup errors open and submits the selected KST baseline',async()=>{const {ui,calls}=harness();const a=asset(tags[0]);register(ui,a);ui.openDataParcRuntimeDialog(a.tagNumber);ui.elements.dataparcRuntimeStartAt.value='2026-05-10T00:00';await ui.submitDataParcRuntimeRange({preventDefault(){}});assert.equal(calls.length,0);assert.equal(ui.elements.dataparcRuntimeDialog.open,true);ui.elements.dataparcRuntimeSourceTag.value=signal;await ui.submitDataParcRuntimeRange({preventDefault(){}});assert.equal(calls.length,0);ui.elements.dataparcRuntimeConfirmSignal.checked=true;await ui.submitDataParcRuntimeRange({preventDefault(){}});assert.equal(Date.parse(calls[0].body.startAt),Date.parse('2026-05-09T15:00:00.000Z'));assert.equal(ui.elements.dataparcRuntimeDialog.open,false);});
test('mobile, public and duplicate submissions are blocked; new manure requires a real replacement',async()=>{for(const options of [{mobile:true},{canWrite:false}]){const {ui,calls}=harness(options);const a=asset(tags[0]);register(ui,a);assert.doesNotMatch(ui.renderAssetCard(a,{}),/data-asset-action="dataparc_runtime_probe"/);await ui.syncDataParcBlowerRuntime(tags[0],'',{dataParcTag:signal,confirmRunSignal:true});assert.equal(calls.length,0);}const {ui,calls}=harness();ui.state.dataparcRuntimeBusy=true;await ui.syncDataParcBlowerRuntime(tags[0],'',{dataParcTag:signal,confirmRunSignal:true});assert.equal(calls.length,0);ui.state.dataparcRuntimeBusy=false;const a=asset(tags.at(-1),{lastReplacementAt:null,isRunning:false,operationState:'unknown',cycleStartState:'pending'});register(ui,a);assert.doesNotMatch(ui.renderAssetCard(a,{}),/data-asset-action="dataparc_runtime_probe"/);assert.match(ui.renderAssetCard(a,{}),/최근 교체일 없음/);});
test('editing the selected signal clears its previous confirmation',()=>{assert.match(source,/dataparcRuntimeSourceTag\.addEventListener\("input"/);assert.match(source,/dataparcRuntimeConfirmSignal\.checked = unchanged && Boolean/);assert.equal((html.match(/id="dataparcRuntimeSourceTag"/g)||[]).length,1);assert.match(html,/<details class="dataparc-runtime-source-settings"/);});
