import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {createRequire} from 'node:module';
import {DatabaseSync} from 'node:sqlite';
import {__blowerHistoryTest as api} from '../functions/api/blower-history.js';
const core=createRequire(import.meta.url)('../maintenance/blower-unified-refresh.js');
const NOW=new Date('2026-09-09T06:00:00.000Z');
const REPL='2026-08-01T00:00:00.000Z',ANCHOR='2026-09-08T06:00:00.000Z';
const TAGS=['104HHL60AP611','104HHL60AP621','104HHL60AP631','204HHL60AP611','204HHL60AP621','204HHL60AP631','104HHL10AN611','104HHL10AN621','104HHL10AN631','204HHL10AN611','204HHL10AN621','204HHL10AN631'];
const OTHER=['104SDF01AN001','104SDF01AN002','204SDF01AN001','204SDF01AN002','104ETG30AN601','104ETG30AN602','204ETG30AN601','204ETG30AN602','104ETH03AN601','104ETH03AN602','204LMDF01AN001'];
const SIGNAL='GSPOGE.ABB_DCS.TEST_ONLY_CONFIRMED_BINARY';
function asset(tag=TAGS[0],extra={}){return {tag_number:tag,blower_type:tag.includes('60AP')?'fbhe':'seal_pot',last_replacement_at:REPL,cycle_start_state:'started',cycle_started_at:'2026-09-08T00:00:00.000Z',cycle_start_revision:'s1',cycle_runtime_revision:'r1',cycle_runtime_anchor_at:ANCHOR,cycle_runtime_hours:50.5,cycle_runtime_state:'running',runtime_hours:50.5,is_running:1,runtime_anchor_at:ANCHOR,...extra};}
function manual(a,extra={}){return {id:'m',tag_number:a.tag_number,event_type:'runtime_correction',event_date:ANCHOR,runtime_hours:50.5,source_type:'manual',source_log_id:'',source_text:'',action_type:'운전중',issue_type:'',note:'직접 확인한 시간 입력',created_at:ANCHOR,updated_at:ANCHOR,...extra};}
function dp(a,extra={}){const s={schemaVersion:1,requestType:'blower_runtime_probe',requestId:'q1',assetTag:a.tag_number,dataParcTag:SIGNAL,startAt:REPL,endAt:ANCHOR,observedAt:ANCHOR,expectedLastReplacementAt:REPL,expectedCycleStartState:a.cycle_start_state,expectedCycleStartedAt:a.cycle_started_at,expectedCycleStartRevision:'s1',expectedCycleRuntimeRevision:'r0',startState:'stopped',endState:'running',totalRunningHours:50.5};return {...manual(a),id:'dataparc_runtime:q1',source_type:'dataparc_runtime',source_log_id:'q1',source_text:JSON.stringify(s),issue_type:'DataPARC',action_type:'DataPARC 운전중 동기화',...extra};}
function asUi(a,extra={}){return {tagNumber:a.tag_number,blowerType:a.blower_type,lastReplacementAt:a.last_replacement_at,cycleStartState:a.cycle_start_state,cycleStartedAt:a.cycle_started_at,cycleStoredStartedAt:a.cycle_started_at,cycleStartRevision:a.cycle_start_revision,cycleRuntimeRevision:a.cycle_runtime_revision,cycleRuntimeState:a.cycle_runtime_state,cycleElapsedHours:a.cycle_runtime_hours,dataParcTag:SIGNAL,enabled:true,...extra};}
for(const tag of TAGS){
 test(`${tag}: old OIS correction saved as manual is NOT a RUN measurement`,()=>{const a=asset(tag),e=manual(a,{note:'OIS 진동 누적시간 적용 · 2026-08-01~2026-09-08'}),before=JSON.stringify([a,e]);const p=api.fbheSealRunProvenance(a,[e],NOW);assert.equal(p.verified,false);assert.equal(p.source,'legacy_ois');assert.equal(p.legacyStoredHours,50.5);assert.equal(JSON.stringify([a,e]),before);});
 test(`${tag}: latest calls DataPARC from replacement, not the old manual first-start date`,()=>{const a=asUi(asset(tag));const p=core.plan([a],NOW);assert.equal(p.tasks.length,1);assert.equal(p.tasks[0].startAt,REPL);assert.equal(p.tasks[0].dataParcTag,SIGNAL);assert.equal(p.tasks[0].kind,'dataparc');});
 test(`${tag}: successful query is verified only with matching source, anchor, hours and state`,()=>{const a=asset(tag),e=dp(a);const p=api.fbheSealRunProvenance(a,[e],NOW);assert.equal(p.source,'dataparc');assert.equal(p.verified,true);assert.equal(p.measuredAt,ANCHOR);assert.equal(p.state,'running');for(const delta of [{cycle_runtime_hours:51},{cycle_runtime_anchor_at:'2026-09-08T07:00:00.000Z'},{cycle_runtime_state:'stopped'},{cycle_start_revision:'s2'}])assert.equal(api.fbheSealRunProvenance({...a,...delta},[e],NOW).verified,false);});
 test(`${tag}: delete restores measured boundary without adding the last 24h`,()=>{const a=asset(tag),r={id:'replacement',event_date:REPL},e=manual(a);const p=api.historyDeleteRestoreBoundary(e,r,NOW,a);assert.equal(p.cycle_runtime_hours,50.5);assert.equal(p.runtime_hours,50.5);assert.equal(p.cycle_runtime_anchor_at,ANCHOR);assert.equal(p.runtime_anchor_at,ANCHOR);});
 test(`${tag}: replacement-edit undo snapshot cannot add wall clock hours`,()=>{const a=asset(tag),r={event_date:REPL},e={tag_number:tag,source_text:JSON.stringify({replacementEdit:true,before:{lastReplacementAt:REPL,cycleStartState:'started',cycleStartedAt:a.cycle_started_at,cycleRuntimeHours:50.5,cycleRuntimeAnchorAt:ANCHOR,cycleRuntimeState:'running'}})};const p=api.historyDeleteRestoreBeforeSnapshot(e,r,NOW);assert.equal(p.cycle_runtime_hours,50.5);assert.equal(p.cycle_runtime_anchor_at,ANCHOR);});
}
for(const tag of OTHER)test(`${tag}: existing normal group keeps its original projection and manual-start planning`,()=>{assert.equal(api.fbheSealRunProvenance(asset(tag),[],NOW),null);assert.equal(core.fbheSealRunView(asUi(asset(tag))),null);const a=asUi(asset(tag));const p=core.plan([a],NOW);assert.equal(p.tasks[0].startAt,a.cycleStartedAt);});
test('manual startup equality is not evidence, including a zero-hour startup',()=>{for(const hours of [0,50.5]){const a=asset(undefined,{cycle_runtime_hours:hours});const e=manual(a,{event_type:'startup',runtime_hours:hours,action_type:'기동'});assert.equal(api.fbheSealRunProvenance(a,[e],NOW).verified,false);}});
test('numeric manual correction stays supported and is honestly labelled manual',()=>{const a=asset(),e=manual(a);const p=api.fbheSealRunProvenance(a,[e],NOW);assert.equal(p.verified,true);assert.equal(p.source,'manual');const v=core.fbheSealRunView(asUi(a,{runRuntime:p}));assert.equal(v.primary,'50.5시간');assert.equal(v.sourceLabel,'수동 보정');assert.equal(v.stateLabel,'수동 기동중');assert.equal(v.basis,null);});
test('older same-number manual row cannot certify a new stored anchor',()=>{const a=asset(),e=manual(a,{event_date:REPL});assert.equal(api.fbheSealRunProvenance(a,[e],NOW).verified,false);});
test('null, missing, empty, boolean and nonfinite values never certify measured zero',()=>{for(const bad of [null,undefined,'',true,'NaN',Infinity]){const a=asset(undefined,{cycle_runtime_hours:0});assert.equal(api.fbheSealRunProvenance(a,[manual(a,{runtime_hours:bad})],NOW).verified,false);}});
test('same-value manual override after DataPARC is not still advertised as DataPARC',()=>{const a=asset(),d=dp(a),m=manual(a,{updated_at:'2026-09-08T06:00:01.000Z',created_at:'2026-09-08T06:00:01.000Z'});const p=api.fbheSealRunProvenance(a,[d,m],NOW);assert.equal(p.source,'manual');assert.equal(p.verified,true);});
test('replacement date edits with derived interval or unverified sentinel never certify hours',()=>{const a=asset();for(const evidence of [{replacementEdit:true},{replacementEdit:true,requiresRunRefresh:true}])assert.equal(api.fbheSealRunProvenance(a,[manual(a,{source_text:JSON.stringify(evidence)})],NOW).verified,false);});
test('DataPARC wrong asset, invented event id or nonbinary end state are rejected by projection',()=>{const a=asset(),e=dp(a);for(const x of [{assetTag:TAGS[1]},{endState:'1'},{endState:1},{endState:2},{requestId:'different'}]){const e2={...e,source_text:JSON.stringify({...JSON.parse(e.source_text),...x})};assert.equal(api.fbheSealRunProvenance(a,[e2],NOW).verified,false);}});
test('manual-first-start never overwrites a cycle-local successful range',()=>{const a=asUi(asset(),{dataParcRuntimeBasis:{startAt:'2026-08-20T00:00:00.000Z'}});assert.equal(core.plan([a],NOW).tasks[0].startAt,'2026-08-20T00:00:00.000Z');});
test('missing source shows setup need, not legacy 50.5h or normal state',()=>{const a=asUi(asset(),{dataParcTag:'',runRuntime:{verified:false,source:'legacy_ois'}}),v=core.fbheSealRunView(a);assert.equal(v.primary,'RUN 조회 전');assert.equal(v.state,'unknown');assert.match(v.message,/RUN TAG 연결 필요/);assert.equal(core.plan([a],NOW).tasks.length,0);});
test('changed cycle with configured source shows requery need, no fake zero',()=>{const v=core.fbheSealRunView(asUi(asset(),{cycleElapsedHours:null,measurementRequired:true,runRuntime:{verified:false}}));assert.equal(v.primary,'RUN 재조회 필요');assert.equal(v.hours,null);});
test('pending and missing replacement retain explicit original safety gates',()=>{assert.equal(core.plan([asUi(asset(undefined,{cycle_start_state:'pending'}))],NOW).tasks.length,0);assert.equal(core.plan([asUi(asset(undefined,{last_replacement_at:''}))],NOW).tasks.length,0);});

function d1(sql){const db={prepare(text){return {v:[],bind(...v){assert.ok(v.length<=100);this.v=v;return this;},async first(){return sql.prepare(text).get(...this.v)||null;},async all(){return {results:sql.prepare(text).all(...this.v)};},async run(){return {meta:{changes:Number(sql.prepare(text).run(...this.v).changes)}};}};},async batch(stmts){sql.exec('BEGIN');try{const out=[];for(const s of stmts)out.push(await s.run());sql.exec('COMMIT');return out;}catch(e){sql.exec('ROLLBACK');throw e;}}};return db;}
async function fixture(tag=TAGS[0]){const sql=new DatabaseSync(':memory:'),db=d1(sql);await api.ensureSchema(db);const r='2020-01-01T00:00:00.000Z',a='2020-01-02T00:00:00.000Z';sql.prepare(`UPDATE blower_history_assets SET last_replacement_at=?,cycle_started_at=?,cycle_start_state='started',cycle_start_revision='s1',cycle_runtime_hours=50.5,cycle_runtime_anchor_at=?,cycle_runtime_state='running',cycle_runtime_revision='r1',runtime_hours=50.5,is_running=1,runtime_anchor_at=? WHERE tag_number=?`).run(r,a,a,a,tag);const add=row=>{const d={id:'rep',tag_number:tag,event_type:'replacement',event_date:r,runtime_hours:0,issue_type:'',action_type:'교체',note:'교체 이력',source_type:'manual',source_log_id:'',source_text:'',created_by_id:'tester',created_by_name:'시험',created_at:r,updated_at:r,...row};sql.prepare(`INSERT INTO blower_history_events (${Object.keys(d).join(',')}) VALUES (${Object.keys(d).map(()=>'?').join(',')})`).run(...Object.values(d));return d;};add({});return {sql,db,add,r,a,tag};}
test('production loadAssetStates hides legacy OIS hours without changing any stored row',async()=>{const f=await fixture();try{f.add({id:'ois',event_type:'runtime_correction',event_date:f.a,runtime_hours:50.5,action_type:'운전중',note:'OIS 진동 누적시간 적용',created_at:f.a,updated_at:f.a});const before=JSON.stringify(f.sql.prepare('SELECT * FROM blower_history_assets').all())+JSON.stringify(f.sql.prepare('SELECT * FROM blower_history_events').all());const a=(await api.loadAssetStates(f.db,{fbhe:{cycleDays:90,warningDays:7,criticalDays:3}})).find(x=>x.tagNumber===f.tag);assert.equal(a.cycleElapsedHours,null);assert.equal(a.runtimeHours,null);assert.equal(a.severity,'runtime_unknown');assert.equal(a.remainingHours,null);assert.equal(a.runRuntime.source,'legacy_ois');assert.equal(JSON.stringify(f.sql.prepare('SELECT * FROM blower_history_assets').all())+JSON.stringify(f.sql.prepare('SELECT * FROM blower_history_events').all()),before);}finally{f.sql.close();}});
for(const tag of [TAGS[0],TAGS[6]])test(`${tag}: actual replacement edit changes dates and audits, without manufacturing full interval hours`,async()=>{const f=await fixture(tag);try{const res=await api.editCurrentManualReplacement(f.db,{employeeNo:'tester',name:'시험'},{tagNumber:tag,eventId:'rep',expectedEventUpdatedAt:f.r,expectedLastReplacementAt:f.r,expectedCycleStartRevision:'s1',expectedCycleRuntimeRevision:'r1',eventDate:f.r,operationMode:'running',startupAt:f.a,note:'실제 교체 정정'},{now:new Date('2020-01-10T00:00:00Z')});const body=await res.json();assert.equal(res.status,200,body.message);const row=f.sql.prepare('SELECT * FROM blower_history_assets WHERE tag_number=?').get(tag);assert.equal(row.cycle_runtime_hours,0);assert.equal(row.cycle_started_at,f.a);const correction=f.sql.prepare("SELECT * FROM blower_history_events WHERE event_type='runtime_correction'").get();assert.equal(JSON.parse(correction.source_text).requiresRunRefresh,true);assert.match(correction.note,/RUN 최신화/);assert.equal(f.sql.prepare('SELECT COUNT(*) n FROM blower_history_asset_history').get().n,1);const a=(await api.loadAssetStates(f.db,{})).find(x=>x.tagNumber===tag);assert.equal(a.cycleElapsedHours,null);assert.equal(a.measurementRequired,true);assert.equal(a.runRuntime.verified,false);}finally{f.sql.close();}});

const src=fs.readFileSync(new URL('../maintenance/blower-history.js',import.meta.url),'utf8');
function uiHarness({mobile=false,write=true}={}){function n(){return {value:'',textContent:'',innerHTML:'',hidden:false,disabled:false,required:false,open:false,dataset:{},classList:{add(){},toggle(){},remove(){}},setAttribute(){},removeAttribute(){},replaceChildren(){},focus(){},addEventListener(){},showModal(){this.open=true;},close(){this.open=false;}};}const nodes=new Map();const ctx=vm.createContext({console,clearTimeout(){},setTimeout(){return 0;},HTMLButtonElement:class{},localStorage:{getItem:()=>null},document:{readyState:'loading',body:n(),querySelectorAll:()=>[],addEventListener(){},getElementById(id){if(!nodes.has(id))nodes.set(id,n());return nodes.get(id);}},window:{BlowerUnifiedRefresh:core,matchMedia:()=>({matches:mobile}),setTimeout(fn){fn();}}});const marker='  if (document.readyState === "loading") {';vm.runInContext(src.replace(marker,`globalThis.u={state,elements,cacheElements,renderAssetCard,openAssetHistory,openDataParcRuntimeDialog,updateReplacementEditFields,updateRuntimeEditPreview,historyRuntimeLabel};\n${marker}`),ctx);const u=ctx.u;u.cacheElements();u.state.data={permissions:{canWrite:write},user:write?{name:'시험'}:null,backfill:{hasRun:true,status:'complete'},assets:[],events:[]};return u;}
function renderAsset(kind='unverified'){const a=asUi(asset(),{displayName:'#1호기 FBHE #A',positionLabel:'#A',unitNo:'1',severity:kind==='unverified'?'runtime_unknown':'normal',cycleRuntimeTracked:true,isRunning:true,remainingHours:2109.5,measurementRequired:kind==='unverified'});a.runRuntime=kind==='unverified'?{verified:false,source:'legacy_ois',legacyStoredHours:50.5}:{verified:true,source:kind,measuredAt:ANCHOR,state:'running',legacyStoredHours:50.5};if(kind==='unverified')a.dataParcTag='';a.dataParcRuntimeBasis=kind==='dataparc'?{startAt:REPL,observedAt:ANCHOR,requestId:'q1'}:null;return a;}
for(const kind of ['unverified','manual','dataparc'])test(`real UI ${kind}: source and actions match the current provenance`,()=>{const u=uiHarness(),a=renderAsset(kind);u.state.data.assets=[a];const html=u.renderAssetCard(a,{cycleDays:90});assert.equal((html.match(/data-asset-action=/g)||[]).length,2);assert.match(html,/V-Belt 교체 등록/);assert.match(html,/이력 보기/);assert.doesNotMatch(html,/data-asset-action="(?:runtime_state|dataparc|startup)"/);if(kind==='unverified'){assert.match(html,/RUN TAG 연결 필요/);assert.match(html,/RUN 조회 전/);assert.doesNotMatch(html,/50\.5시간/);assert.match(html,/data-operation-state="unknown"/);}else if(kind==='manual'){assert.match(html,/수동 보정/);assert.match(html,/50\.5시간/);}else {assert.match(html,/DataPARC · RUN 1\/0/);assert.match(html,/2026-08-01 09:00 → 2026-09-08 15:00/);assert.match(html,/50\.5시간/);assert.match(html,/D-/);}assert.doesNotMatch(html,/<em>기동<\/em>/);});
test('real setup dialog defaults to replacement and never fills an inferred RUN TAG',()=>{const u=uiHarness(),a=renderAsset('unverified');u.state.data.assets=[a];u.openDataParcRuntimeDialog(a.tagNumber);assert.equal(u.elements.dataparcRuntimeDialog.open,true);assert.equal(u.elements.dataparcRuntimeStartAt.value,'2026-08-01T09:00');assert.equal(u.elements.dataparcRuntimeSourceTag.value,'');assert.match(u.elements.dataparcRuntimeSourceHelp.textContent,/임의로 AP\/AN/);assert.equal(u.elements.dataparcRuntimeConfirmSignal.checked,false);});
test('real setup keeps a prior successful cycle-local start',()=>{const u=uiHarness(),a=renderAsset('dataparc');a.dataParcRuntimeBasis.startAt='2026-08-20T00:00:00Z';u.state.data.assets=[a];u.openDataParcRuntimeDialog(a.tagNumber);assert.equal(u.elements.dataparcRuntimeStartAt.value,'2026-08-20T09:00');assert.equal(u.elements.dataparcRuntimeSourceTag.value,SIGNAL);});
test('public and mobile still cannot open RUN setup or acquire write controls',()=>{for(const options of [{mobile:true},{write:false}]){const u=uiHarness(options),a=renderAsset();u.state.data.assets=[a];u.openDataParcRuntimeDialog(a.tagNumber);assert.equal(u.elements.dataparcRuntimeDialog.open,false);u.openAssetHistory(a.tagNumber);assert.equal(u.elements.historyRuntimeQueryButton.hidden,true);}});
test('history keeps the previous storage value separate and labels unverified sentinels',()=>{const u=uiHarness(),a=renderAsset();u.state.data.assets=[a];u.openAssetHistory(a.tagNumber);assert.match(u.elements.historyCycleSummary.innerHTML,/기존 저장값 50\.5시간은 RUN 확인값이 아닙니다/);assert.equal(u.historyRuntimeLabel({tagNumber:a.tagNumber,sourceText:'{"requiresRunRefresh":true}',runtimeHours:0}),'RUN 재조회 필요');});

for(const eventType of ['operation_start','operation_stop'])test(`target ${eventType} edit preview never projects continuous clock hours`,()=>{const u=uiHarness(),a=renderAsset('manual'),e={id:'boundary',tagNumber:a.tagNumber,eventType,eventDate:ANCHOR,runtimeHours:50.5,sourceType:'manual'};u.state.data.assets=[a];u.state.data.events=[e];u.elements.recordMode.value='runtime_state_edit';u.elements.recordTag.value=a.tagNumber;u.elements.recordEventId.value=e.id;u.elements.recordDate.value='2026-09-08T18:00';u.updateRuntimeEditPreview();assert.match(u.elements.runtimeCycleSummary.innerHTML,/RUN 재조회 필요/);assert.match(u.elements.runtimeCycleSummary.innerHTML,/더하지 않습니다/);assert.doesNotMatch(u.elements.runtimeCycleSummary.innerHTML,/현재 누적|Cycle 계산을 이어갑니다/);});

// The actual Agent/API persistence contract converts binary 1/0 into
// "running"/"stopped" strings. Exercise real sync, not handcrafted audit only.
for(const [index,tag] of TAGS.entries())test(`${tag}: actual DataPARC sync is recognized by the next production read`,async()=>{
 const f=await fixture(tag);
 try {
  const end='2020-01-03T00:00:00.000Z',collected='2020-01-03T00:00:30.000Z';
  const stopped=index%2===0, seconds=stopped?0:45001, hours=seconds/3600;
  const probe={schemaVersion:1,requestType:'blower_runtime_probe',requestId:'real-contract-'+tag,ok:true,readOnly:true,
   assetTag:tag,dataParcTag:SIGNAL,startAt:f.r,endAt:end,observedAt:end,collectedAt:collected,
   expectedLastReplacementAt:f.r,expectedCycleStartState:'started',expectedCycleStartedAt:f.a,
   expectedCycleStartRevision:'s1',expectedCycleRuntimeRevision:'r1',startState:'stopped',endState:stopped?'stopped':'running',
   totalRunningHours:hours,runningSeconds:seconds,chunkDays:31,chunkCount:1,completedChunkCount:1,
   chunks:[{index:1,startAt:f.r,endAt:end,startState:'stopped',endState:stopped?'stopped':'running',totalRunningHours:hours,runningSeconds:seconds}]};
  f.sql.exec(`CREATE TABLE ois_data_requests (id TEXT PRIMARY KEY,request_type TEXT,status TEXT,target_date TEXT,requested_by_id TEXT,result_json TEXT,completed_at TEXT);
   CREATE TABLE blower_runtime_probe_intents_v4(request_id TEXT PRIMARY KEY,schema_version INTEGER,asset_tag TEXT,dataparc_tag TEXT,window_start TEXT,window_end TEXT,chunk_days INTEGER,chunk_count INTEGER,expected_last_replacement_at TEXT,expected_cycle_start_state TEXT,expected_cycle_started_at TEXT,expected_cycle_start_revision TEXT,expected_cycle_runtime_revision TEXT);`);
  f.sql.prepare('INSERT INTO ois_data_requests VALUES (?,?,?,?,?,?,?)').run(probe.requestId,probe.requestType,'complete',`v1|${tag}|${f.r}|${end}`,'tester',JSON.stringify(probe),collected);
  f.sql.prepare('INSERT INTO blower_runtime_probe_intents_v4 VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)').run(probe.requestId,1,tag,SIGNAL,f.r,end,31,1,f.r,'started',f.a,'s1','r1');
  const response=await api.applyDataParcRuntimeSync(f.db,{employeeNo:'tester',name:'시험'},{requestId:probe.requestId},{now:new Date('2020-01-03T00:01:00Z')});
  const body=await response.json();assert.equal(response.status,200,body.message);
  const a=(await api.loadAssetStates(f.db,{fbhe:{cycleDays:90,warningDays:7,criticalDays:3}})).find(a=>a.tagNumber===tag);
  assert.equal(a.runRuntime.source,'dataparc');assert.equal(a.runRuntime.verified,true);assert.equal(a.runRuntime.measuredAt,end);
  assert.equal(a.cycleElapsedHours,hours);assert.equal(a.isRunning,!stopped);assert.equal(a.dataParcTag,SIGNAL);
  const view=core.fbheSealRunView(a,a.dataParcRuntimeBasis);assert.equal(view.verified,true);assert.equal(view.basis.startAt,f.r);assert.equal(view.state,probe.endState);
  assert.equal(view.primary,stopped?'0.0시간':'12.5시간');assert.equal(f.sql.prepare("SELECT COUNT(*) n FROM blower_history_events WHERE event_type='replacement'").get().n,1);
 } finally {f.sql.close();}
});

test('manual value without a connected RUN signal still exposes the setup requirement',()=>{const a=asUi(asset(),{dataParcTag:'',runRuntime:{verified:true,source:'manual',state:'running',measuredAt:ANCHOR}});const v=core.fbheSealRunView(a);assert.equal(v.primary,'50.5시간');assert.equal(v.sourceLabel,'수동 보정');assert.match(v.message,/RUN TAG 연결 필요/);});
