import test from 'node:test';
import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import { createRequire } from 'node:module';
import { __blowerHistoryTest as api } from '../functions/api/blower-history.js';
const core=createRequire(import.meta.url)('../maintenance/blower-unified-refresh.js');
const NOW=new Date('2026-09-09T01:00:00.000Z'),USER={employeeNo:'delta-test',name:'증분 시험'};
async function fixture(){
 const sql=new DatabaseSync(':memory:');let batches=Promise.resolve();
 const db={fail:null,rowsReturned:[],prepare(text){return {values:[],bind(...v){this.values=v;return this;},
  async run(){if(db.fail?.(text,this.values))throw new Error('D1_ERROR: injected retryable failure');return {meta:{changes:Number(sql.prepare(text).run(...this.values).changes)}};},
  async all(){if(db.fail?.(text,this.values))throw new Error('D1_ERROR: injected retryable failure');const rows=sql.prepare(text).all(...this.values);db.rowsReturned.push({text,rows});return {results:rows};},
  async first(){if(db.fail?.(text,this.values))throw new Error('D1_ERROR: injected retryable failure');return sql.prepare(text).get(...this.values)||null;}};},
  async batch(items){let release;const prior=batches;batches=new Promise(r=>release=r);await prior;sql.exec('BEGIN IMMEDIATE');try{const out=[];for(const s of items)out.push(await s.run());sql.exec('COMMIT');return out;}catch(e){sql.exec('ROLLBACK');throw e;}finally{release();}}};
 await api.ensureSchema(db);
 sql.exec('CREATE TABLE shift_logs(id TEXT PRIMARY KEY,work_date TEXT,shift TEXT,role TEXT,author TEXT,status TEXT,log_json TEXT,updated_at TEXT);');
 function add(id,overrides={}){const a={id,work_date:'2026-09-08',shift:'D/S',role:'BCO1',author:'테스트',status:'결재완료',log_json:JSON.stringify({entries:[{time:'10:00',content:'일상 점검 완료'}]}),updated_at:'2026-09-08T10:00:00.000Z',...overrides};sql.prepare(`INSERT INTO shift_logs(${Object.keys(a)}) VALUES(${Object.keys(a).map(()=>'?')})`).run(...Object.values(a));}
 const step=async(body={})=>{const r=await api.latestLogsStep(db,USER,{phase:'replacement',incrementalLogs:true,limit:4,...body},{now:NOW});return {status:r.status,...await r.json()};};
 const pass=async(phase='replacement')=>{let n=0,window=null;for(let i=0;i<100;i++){const p=await step({phase,window});assert.equal(p.status,200,JSON.stringify(p));window=p.window;n+=p.scannedLogCount;if(p.done)return n;}throw new Error('not finished');};
 return {sql,db,add,step,pass,close:()=>sql.close()};
}
test('unchanged approved logs are parsed once per phase; future refresh returns no raw log pages',async()=>{const f=await fixture();try{for(let i=0;i<15;i++)f.add('log'+i);assert.equal(await f.pass(),15);assert.equal(await f.pass('operation'),15);f.db.rowsReturned=[];assert.equal(await f.pass(),0);assert.equal(await f.pass('operation'),0);assert.equal(f.sql.prepare('SELECT COUNT(*) n FROM blower_log_receipts_v1').get().n,15);assert.ok(f.db.rowsReturned.filter(x=>x.text.includes('FROM shift_logs AS l')).every(x=>x.rows.length===0));}finally{f.close();}});
test('new day only brings new logs, while unchanged previous day remains untouched',async()=>{const f=await fixture();try{f.add('old');await f.pass();await f.pass('operation');const receipt=f.sql.prepare('SELECT * FROM blower_log_receipts_v1 WHERE log_id=?').get('old');f.add('today',{work_date:'2026-09-09',updated_at:'2026-09-09T00:00:00Z'});assert.equal(await f.pass(),1);assert.equal(await f.pass('operation'),1);assert.deepEqual(f.sql.prepare('SELECT * FROM blower_log_receipts_v1 WHERE log_id=?').get('old'),receipt);}finally{f.close();}});
for(const mutation of ['updated','same-stamp-body','null-stamp-body','late-approval','role','author','workdate'])test(`a past log ${mutation} is rechecked without replaying other completed logs`,async()=>{const f=await fixture();try{
 f.add('same');f.add('change',{updated_at:mutation==='null-stamp-body'?null:'2026-09-08T10:00:00.000Z',status:mutation==='late-approval'?'작성중':'결재완료'});await f.pass();await f.pass('operation');
 if(mutation==='updated')f.sql.prepare('UPDATE shift_logs SET updated_at=? WHERE id=?').run('2026-09-09T00:30:00Z','change');
 else if(mutation==='same-stamp-body'||mutation==='null-stamp-body')f.sql.prepare('UPDATE shift_logs SET log_json=? WHERE id=?').run(JSON.stringify({entries:[{time:'11:00',content:'#1 FBHE Blower #A 104HHL60AP611 V-Belt 교체 완료'}]}),'change');
 else if(mutation==='late-approval')f.sql.exec("UPDATE shift_logs SET status='결재완료' WHERE id='change'");
 else f.sql.prepare(`UPDATE shift_logs SET ${mutation==='workdate'?'work_date':mutation}=? WHERE id='change'`).run(mutation==='workdate'?'2026-09-07':mutation==='role'?'BCO2':'변경자');
 const p=await f.step();assert.equal(p.status,200,JSON.stringify(p));assert.equal(p.scannedLogCount,1);assert.equal(await f.pass('operation'),1);assert.equal(await f.pass(),0);
 }finally{f.close();}});
test('successful page survives page close; no client checkpoint can skip the remaining logs',async()=>{const f=await fixture();try{for(let i=0;i<9;i++)f.add('a'+i);const first=await f.step({limit:2});assert.equal(first.scannedLogCount,2);assert.equal(first.done,false);const second=await f.step({limit:2,cursor:{workDate:'2026-09-09',id:'forged-skip-everything',updatedAt:''}});assert.equal(second.scannedLogCount,2);assert.equal(f.sql.prepare('SELECT COUNT(*) n FROM blower_log_receipts_v1').get().n,4);assert.equal(await f.pass(),5);assert.equal(await f.pass(),0);}finally{f.close();}});
test('503 does not mark failed page complete and never erases successful page receipts',async()=>{const f=await fixture();try{for(let i=0;i<6;i++)f.add('b'+i);await f.step({limit:2});const before=f.sql.prepare('SELECT * FROM blower_log_receipts_v1 ORDER BY log_id').all();f.db.fail=text=>text.includes('INSERT INTO blower_log_receipts_v1');const bad=await f.step({limit:2});assert.equal(bad.status,503);assert.deepEqual(f.sql.prepare('SELECT * FROM blower_log_receipts_v1 ORDER BY log_id').all(),before);f.db.fail=null;assert.equal(await f.pass(),4);assert.equal(await f.pass(),0);}finally{f.close();}});
test('new source version resets only that log phase flags; failure leaves it pending',async()=>{const f=await fixture();try{f.add('one');await f.pass();await f.pass('operation');f.sql.exec("UPDATE shift_logs SET author='late edit' WHERE id='one'");await f.pass();const row=f.sql.prepare("SELECT * FROM blower_log_receipts_v1 WHERE log_id='one'").get();assert.equal(row.replacement_done,1);assert.equal(row.operation_done,0);f.db.fail=text=>text.includes('INSERT INTO blower_log_receipts_v1');assert.equal((await f.step({phase:'operation'})).status,503);f.db.fail=null;assert.equal(await f.pass('operation'),1);}finally{f.close();}});
test('snapshot cutoff defers new edits until next refresh without moving completed checkpoints ahead',async()=>{const f=await fixture();try{f.add('one',{updated_at:'2026-09-09T02:00:00Z'});assert.equal(await f.pass(),0);const next=await api.latestLogsStep(f.db,USER,{phase:'replacement',incrementalLogs:true},{now:new Date('2026-09-09T03:00:00Z')});assert.equal((await next.json()).scannedLogCount,1);}finally{f.close();}});
test('legacy endpoint remains bounded without creating new receipt schema',async()=>{const f=await fixture();try{f.add('one');const r=await f.step({incrementalLogs:false});assert.equal(r.status,200);assert.equal(r.scannedLogCount,1);assert.equal(f.sql.prepare("SELECT COUNT(*) n FROM sqlite_master WHERE name='blower_log_receipts_v1'").get().n,0);}finally{f.close();}});
test('frontend with real log API completes both phases, and next Latest performs zero repeated analyses',async()=>{const f=await fixture();try{for(let i=0;i<11;i++)f.add('c'+i);const calls=[];const io={assertWritable(){},progress(){},api:async opts=>{calls.push(opts.body);const p=await f.step(opts.body);assert.equal(p.status,200,JSON.stringify(p));return p;}};const a=await core.refreshLogs(io,{sleep:async()=>{}});assert.equal(a.scannedReplacementLogs,11);assert.equal(a.scannedOperationLogs,11);const b=await core.refreshLogs(io,{sleep:async()=>{}});assert.equal(b.scannedReplacementLogs,0);assert.equal(b.scannedOperationLogs,0);assert.ok(calls.every(b=>b.incrementalLogs===true));}finally{f.close();}});
test('same-stamp Unicode and JSON escaping are compared exactly in SQLite receipts',async()=>{const f=await fixture();try{f.add('unicode',{author:'가 😀 "',log_json:JSON.stringify({entries:[{time:'10:00',content:'\\경로\n문자 😀 " 내용'}]})});assert.equal(await f.pass(),1);assert.equal(await f.pass(),0);f.sql.exec("UPDATE shift_logs SET author='나 😀' WHERE id='unicode'");assert.equal(await f.pass(),1);}finally{f.close();}});
test('candidate receipts do not auto-confirm replacements or reset measured runtimes',async()=>{const f=await fixture();try{const before=f.sql.prepare('SELECT * FROM blower_history_assets ORDER BY tag_number').all();f.add('belt',{log_json:JSON.stringify({entries:[{time:'10:00',content:'#1 FBHE Blower #A 104HHL60AP611 V-Belt 교체 완료'}]})});const a=await f.step();assert.equal(a.insertedCount,1);assert.equal(await f.pass(),0);const candidates=f.sql.prepare('SELECT * FROM blower_history_candidates').all();assert.equal(candidates.length,1);assert.equal(candidates[0].status,'pending');assert.deepEqual(f.sql.prepare('SELECT * FROM blower_history_assets ORDER BY tag_number').all(),before);}finally{f.close();}});
