import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),core=require('../maintenance/blower-unified-refresh.js');
const now=new Date('2026-09-09T06:00:00Z');
const dp=['104ETH03AN601','104ETH03AN602','104ETG30AN601','104ETG30AN602','204ETG30AN601','204ETG30AN602','104SDF01AN001','104SDF01AN002','204SDF01AN001','204SDF01AN002','204LMDF01AN001'];
function asset(tag,overrides={}){return {tagNumber:tag,blowerType:tag.includes('HHL60')?'fbhe':tag.includes('HHL10')?'seal_pot':tag.includes('SDF')||tag.includes('LMDF')?'organic_fuel':tag.includes('ETG')?'flyash_bag':'flyash_silo',displayName:tag,enabled:true,lastReplacementAt:'2026-09-01T00:00:00+09:00',cycleStartState:'legacy',cycleStoredStartedAt:'',cycleStartedAt:'2026-09-01T00:00:00+09:00',cycleStartRevision:'s1',cycleRuntimeRevision:'r1',dataParcTag:'GSPOGE.ABB_DCS.TEST_ONLY_CONFIRMED_BINARY',...overrides};}
function all(){return [...dp,...['104','204'].flatMap(p=>['60','10'].flatMap(g=>['611','621','631'].map(n=>`${p}HHL${g}AP${n}`)))].map(a=>asset(a.replace('HHL10AP','HHL10AN')));}
test('one plan spans all 23 assets, independent of current tab, with only confirmed binary RUN tasks',()=>{const p=core.plan(all(),now);assert.equal(p.targetCount,23);assert.equal(p.tasks.length,23);assert.equal(p.skipped.length,0);assert.ok(p.tasks.every(t=>t.kind==='dataparc'));assert.equal(new Set(p.tasks.map(t=>t.asset.tagNumber)).size,23);assert.equal(p.tasks[1].dataParcTag,'GSPOGE.ABB_DCS.003ETH03AN602XB04');});
test('successful maintenance baseline is preserved rather than last observation or last stop',()=>{const a=asset(dp[0],{dataParcRuntimeBasis:{startAt:'2026-09-02T00:00:00+09:00',observedAt:'2026-09-08T10:00:00+09:00'},cycleRuntimeAnchorAt:'2026-09-08T10:00:00+09:00'});assert.equal(core.plan([a],now).tasks[0].startAt,a.dataParcRuntimeBasis.startAt);});
test('legacy effective startup does not replace raw database startup in CAS snapshot',()=>{const a=asset(dp[0]);const p=core.plan([a],now);assert.equal(p.tasks[0].snapshot.cycleStartedAt,'');assert.equal(core.sameCycle(a,p.tasks[0].snapshot),true);assert.equal(core.sameCycle({...a,cycleRuntimeRevision:'new'},p.tasks[0].snapshot),false);});
for(const [label,changes] of [['missing replacement',{lastReplacementAt:null}],['future replacement',{lastReplacementAt:'2026-09-10T00:00:00Z'}],['pending',{cycleStartState:'pending'}],['unknown signal',{dataParcTag:''}],['unsafe signal',{dataParcTag:'GSPOGE.ABB_DCS.BAD"TAG'}],['other pilot signal',{dataParcTag:'GSPOGE.ABB_DCS.003ETH03AN602XB04'}],['ancient baseline',{lastReplacementAt:'2024-01-01T00:00:00Z'}],['stale cycle basis',{dataParcRuntimeBasis:{startAt:'2026-08-01T00:00:00Z'}}]])
test(`planner safely skips ${label} without blocking other assets`,()=>{const p=core.plan([asset(dp[0],changes),asset(dp[1])],now);assert.equal(p.skipped.length,1);assert.equal(p.tasks.length,1);assert.ok(p.skipped[0].message);});
test('disabled assets are not included, unknown dynamically registered assets are explicit skips',()=>{const p=core.plan([asset(dp[0],{enabled:false}),asset('CUSTOM')],now);assert.equal(p.targetCount,1);assert.equal(p.skipped.length,1);assert.equal(p.tasks.length,0);});
test('one overrange FBHE cannot prevent remaining confirmed RUN requests',()=>{const p=core.plan([asset('104HHL60AP611',{lastReplacementAt:'2024-01-01T00:00:00Z'}),asset('104HHL60AP621')],now);assert.equal(p.skipped.length,1);assert.equal(p.tasks.length,1);assert.equal(p.tasks[0].asset.tagNumber,'104HHL60AP621');});
test('KST date rollover, no local timezone dependence',()=>{assert.equal(core.day('2026-09-08T15:00:00Z'),'2026-09-09');assert.equal(core.day('2026-09-08T14:59:59Z'),'2026-09-08');assert.equal(core.intermittent(asset(dp.at(-1))),true);});
function clockIo(responses){let ms=0,index=0;const calls=[];return {calls,io:{assertWritable(){},api:async o=>{calls.push(o);const row=responses[Math.min(index++,responses.length-1)];if(row instanceof Error)throw row;return row;}},opts:{clock:()=>ms,sleep:async n=>{ms+=n;},pendingTimeoutMs:10000,timeoutMs:30000}};}
test('poll uses exact IDs and retries transient reads; no mutation request is retried',async()=>{const f=clockIo([Object.assign(new Error('retry'),{status:503}),{items:[{id:'q1',status:'processing'}]},{items:[{id:'q1',status:'complete'}]}]);const out=await core.waitRequests([{id:'q1',status:'pending'}],f.io,f.opts);assert.equal(out[0].status,'complete');assert.equal(f.calls.length,3);assert.ok(f.calls.every(c=>c.url.includes('ids=q1')&&!c.body));});
test('all-pending Agent timeout stops serial queuing without canceling the existing request',async()=>{const f=clockIo([{items:[{id:'q1',status:'pending'}]}]);await assert.rejects(()=>core.waitRequests([{id:'q1',status:'pending'}],f.io,f.opts),e=>e.code==='AGENT_UNAVAILABLE');assert.ok(f.calls.every(c=>!c.body));});
test('missing status, failed result, unauthorized poll, and unknown state are hard failures',async()=>{
 for(const [items,responses,match] of [[[{id:'q1',status:'pending'}],[{items:[]}],/누락/],[[{id:'q1',status:'failed',errorMessage:'bad raw'}],[],/bad raw/],[[{id:'q1',status:'pending'}],[Object.assign(new Error('login expired'),{status:401})],/login expired/],[[{id:'q1',status:'other'}],[],/알 수 없는/]]){const f=clockIo(responses);await assert.rejects(()=>core.waitRequests(items,f.io,f.opts),match);}
});
test('mid-poll loss of write authorization stops before another network call',async()=>{const f=clockIo([{items:[{id:'q1',status:'processing'}]}]);let n=0;f.io.assertWritable=()=>{if(n++>0)throw new Error('readonly');};await assert.rejects(()=>core.waitRequests([{id:'q1',status:'pending'}],f.io,f.opts),/readonly/);assert.equal(f.calls.length,1);});
test('DataPARC create includes immutable snapshot, and apply is only requestId',async()=>{const calls=[],task=core.plan([asset(dp[0])],now).tasks[0];await core.executeDataParc(task,{assertWritable(){},api:async o=>{calls.push(o);return o.body.action==='create_blower_runtime_probe'?{item:{id:'exact',status:'complete'}}:{message:'ok'};}});assert.equal(calls.length,2);assert.equal(calls[0].body.unifiedRefresh,true);assert.equal(calls[0].body.expectedCycleStartedAt,'');assert.deepEqual(calls[1].body,{action:'dataparc_runtime_sync',requestId:'exact'});});
test('legacy OIS bridge (not the Latest path) requests latest endpoints and use the existing analysis bridge',async()=>{for(const kind of ['fbhe','seal_pot']){const task={kind,startDate:'2026-09-01',endDate:'2026-09-09'},calls=[];core.register(kind,async(t,items)=>{assert.equal(t,task);assert.equal(items[0].id,'q1');return [{status:'complete'}];});const result=await core.executeOis(task,{api:async o=>{calls.push(o);return {items:[{id:'q1',status:'complete'}]};}});assert.equal(calls[0].body.refreshLatest,true);assert.equal(calls[0].body.forceRefresh,undefined);assert.equal(result.length,1);}});
test('OIS request is atomic even for a no-delta plan; bad no-delta reports cannot verify',()=>{const a=asset('104HHL60AP611'),task={kind:'fbhe',snapshots:[core.snapshot(a)]},p={runtimeReason:'',stateFresh:true,cycleRuntimeHours:2,latestSampleAt:now.toISOString(),cycleCoveragePct:100,rangeCoveragePct:100,stateEligible:true,targetRunning:false};const b=core.oisBody(task,[{id:'q1'}],a,p,now.toISOString());assert.equal(b.action,'ois_runtime_refresh_apply');assert.equal(b.targetState,'stopped');assert.equal(b.expectedCycleStartedAt,'');assert.throws(()=>core.oisBody(task,[],a,{...p,runtimeReason:'95% 미만'},now.toISOString()),/95%/);assert.throws(()=>core.oisBody(task,[],a,{...p,stateFresh:false},now.toISOString()),/3시간/);assert.throws(()=>core.oisBody(task,[],{...a,cycleRuntimeRevision:'changed'},p,now.toISOString()),/이력이 변경/);});
