'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const crypto=require('node:crypto');
const root=path.resolve(__dirname,'..');
const read=rel=>fs.readFileSync(path.join(root,rel));
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const norm=s=>String(s).replace(/^\uFEFF/,'').replace(/\r\n/g,'\n').replace(/\r/g,'\n');
const script=norm(read('script.js').toString('utf8'));
const providerBytes=read('maintenance/to-night-power.js');
const provider=norm(providerBytes.toString('utf8'));
const html=norm(read('index.html').toString('utf8'));
const CORE_START="/* STRUCTURE V17 TO POWER RENDER CORE R3 START */";
const CORE_END="/* STRUCTURE V17 TO POWER RENDER CORE R3 END */";
test('V17 R3 exact reviewed artifact hashes are present',()=>{assert.equal(sha(read('script.js')),'29b7decc6f25d93c2d75e2332f8bb001ff8f29632097f6a8572c4476591461b8');assert.equal(sha(providerBytes),'ba2987d7062b60e8c5547970fbdcaf56c5ca97e462b7e5dcdf60df123d244efe');assert.match(provider,/8bd09c6e384e25e2afaa788a5d8a50c84a45cd51a325ee0293b67b34f7db3400/);});
test('V17 R3 keeps the existing loader chain unchanged',()=>{assert.equal((html.match(/maintenance\/to-night-power-render-core\.js/g)||[]).length,0);assert.equal((html.match(/maintenance\/to-night-power\.js/g)||[]).length,1);const main=html.indexOf('script.js');const p=html.indexOf('maintenance/to-night-power.js');assert.ok(main>=0&&p>main);});
test('existing TO provider body is byte-semantic-identical after the V17 prefix',()=>{const end=provider.indexOf(CORE_END);assert.ok(end>=0);const suffix=provider.slice(end+CORE_END.length).replace(/^\n+/, '');assert.equal(sha(Buffer.from(norm(suffix))),'511dc088f5f7b6a18b8d8e74f1b1e94036251bb762af33a53d9ee1d2bc4dc478');});
test('script prefers provider core and preserves the compact six-field compatibility fallback',()=>{assert.equal((script.match(/window\.GSToNightPowerRenderCore/g)||[]).length,1);assert.equal((script.match(/renderDailyPowerV17/g)||[]).length,3);assert.match(script,/typeof renderDailyPowerV17 ===\s*"function"/);assert.match(script,/Compatibility fallback/);assert.match(script,/const powerRowsV17 = \[/);assert.match(script,/for \(\s*const \[powerElement, powerValue\] of/);for(const f of ["solarDailyGeneration","solarMonthlyCumulative","solarYearlyCumulative","generatorEcmsGen1","ismartReception","epowerTransmission"])assert.match(script,new RegExp('\[elements\.'+f+', '+f+'\]'));});
test('provider render core is pure and preserves six-field hide/show behavior',()=>{const a=provider.indexOf(CORE_START),b=provider.indexOf(CORE_END);assert.ok(a>=0&&b>a);const core=provider.slice(a,b+CORE_END.length);for(const bad of ['fetch(','XMLHttpRequest','localStorage','sessionStorage','/api/','indexedDB'])assert.equal(core.includes(bad),false,bad);const sandbox={window:{}};sandbox.globalThis=sandbox.window;vm.createContext(sandbox);vm.runInContext(core,sandbox);const api=sandbox.window.GSToNightPowerRenderCore;assert.equal(api.version,'20260927-structure-v17-r3');for(const hideValues of [true,false]){const elements={};for(const f of ["solarDailyGeneration","solarMonthlyCumulative","solarYearlyCumulative","generatorEcmsGen1","ismartReception","epowerTransmission"])elements[f]={textContent:'seed'};const values={solarDailyGeneration:1.25,solarMonthlyCumulative:2.5,solarYearlyCumulative:3.75,generatorEcmsGen1:4,ismartReception:5,epowerTransmission:6};api.renderDailyPower({elements,hideValues,formatAmount:(v,u)=>String(v)+' '+u,...values});for(const f of ["solarDailyGeneration","solarMonthlyCumulative","solarYearlyCumulative","generatorEcmsGen1","ismartReception","epowerTransmission"])assert.equal(elements[f].textContent,hideValues?'-':String(values[f])+' kWh');}});
