param(
  [string]$Repo = 'C:\Users\GSENR\Desktop\gs-shift-log'
)

$ErrorActionPreference = 'Stop'
Set-Location $Repo

$Agent =
  Join-Path $Repo 'local-tools\ois-agent\ois-login.js'

$Node =
  'C:\Program Files\nodejs\node.exe'

if (-not (Test-Path -LiteralPath $Agent)) {
  throw "Agent file not found: $Agent"
}

if (-not (Test-Path -LiteralPath $Node)) {
  throw "Node.exe not found: $Node"
}

function Get-NewLine {
  param([string]$Text)

  if ($Text.Contains("`r`n")) {
    return "`r`n"
  }

  return "`n"
}

function Convert-NewLine {
  param(
    [string]$Text,
    [string]$NewLine
  )

  return $Text
    .Replace("`r`n", "`n")
    .Replace("`r", "`n")
    .Replace("`n", $NewLine)
}

function Replace-Range {
  param(
    [string]$Text,
    [int]$Start,
    [int]$End,
    [string]$Replacement
  )

  if (
    $Start -lt 0 -or
    $End -lt $Start -or
    $End -gt $Text.Length
  ) {
    throw "Invalid replacement range: $Start .. $End"
  }

  return (
    $Text.Substring(0, $Start) +
    $Replacement +
    $Text.Substring($End)
  )
}

Write-Host '===== Phase 3.4A v2 Silo request trace ====='

Write-Host ''
Write-Host '===== Pre-patch syntax check ====='

& $Node --check $Agent

if ($LASTEXITCODE -ne 0) {
  throw 'Agent syntax is already invalid before patch.'
}

$Text =
  [IO.File]::ReadAllText($Agent)

if ($Text.Contains('[PHASE3.4A SILO AJAX TRACE]')) {
  throw 'Phase 3.4A trace is already applied.'
}

foreach (
  $Required in @(
    '[PHASE3.3B NONBLOCKING STARTUP]',
    '[PHASE3.3A EXCEL BULK READ]',
    '[PHASE3.2 WATER DIRECT]'
  )
) {
  if (-not $Text.Contains($Required)) {
    throw "Required marker missing: $Required"
  }
}

$Stamp =
  Get-Date -Format 'yyyyMMdd-HHmmss'

$Backup =
  "$Agent.before-phase34a-v2-$Stamp.bak"

Copy-Item `
  -LiteralPath $Agent `
  -Destination $Backup `
  -Force

Write-Host "Backup: $Backup"

$Nl =
  Get-NewLine $Text

try {
  $FunctionStart =
    $Text.IndexOf(
      'async function collectOisSiloLevelValues('
    )

  if ($FunctionStart -lt 0) {
    throw 'collectOisSiloLevelValues was not found.'
  }

  $NextAnchor =
    '/* =========================================================' +
    $Nl +
    '  OIS 과거 LOG SHEET 업무일지 조회 정의'

  $FunctionEnd =
    $Text.IndexOf(
      $NextAnchor,
      $FunctionStart
    )

  if ($FunctionEnd -lt 0) {
    throw 'The anchor after collectOisSiloLevelValues was not found.'
  }

  $OldFunction =
    $Text.Substring(
      $FunctionStart,
      $FunctionEnd - $FunctionStart
    )

  foreach (
    $Expected in @(
      'const capturedValues = {};',
      'await openOisTagLogLookup(',
      'await setOisTagLogSearchConditions(',
      'await captureOisTagLog24HourValueFromApi(',
      'OIS Silo Level 조회 완료'
    )
  ) {
    if (-not $OldFunction.Contains($Expected)) {
      throw "Existing Silo function does not contain expected text: $Expected"
    }
  }

  $NewFunction =
    Convert-NewLine `
      -NewLine $Nl `
      -Text @'
async function collectOisSiloLevelValues(
  page,
  config,
  targetDate
) {
  if (
    !isValidOisAgentDate(
      targetDate
    )
  ) {
    throw new Error(
      "Silo Level 조회 날짜가 올바르지 않습니다."
    );
  }


  await ensureOisAgentLoggedIn(
    page,
    config
  );


  /*
    [PHASE3.4A SILO AJAX TRACE]

    Diagnostic only.
    Capture the exact /ajax/data request body generated by
    the existing TAG Log UI for the two Silo tags.

    No request is changed or replayed here.
  */
  const phase34SiloStartedAt =
    Date.now();


  const phase34RequestListener =
    request => {
      try {
        const requestUrl =
          String(
            request.url() ||
            ""
          );

        const requestMethod =
          String(
            request.method() ||
            ""
          ).toUpperCase();

        if (
          !requestUrl.includes(
            "/ajax/data"
          ) ||
          requestMethod !==
            "POST"
        ) {
          return;
        }


        const rawBody =
          String(
            request.postData() ||
            ""
          );

        const upperBody =
          rawBody.toUpperCase();

        const isSiloRequest =
          OIS_SILO_LEVEL_DEFINITIONS
            .some(
              definition =>
                upperBody.includes(
                  String(
                    definition.tag ||
                    ""
                  ).toUpperCase()
                )
            );

        if (
          !isSiloRequest
        ) {
          return;
        }


        const parameters =
          new URLSearchParams(
            rawBody
          );

        const command =
          parameters.get(
            "cmd"
          ) ||
          parameters.get(
            "CMD"
          ) ||
          "";

        const tossdata =
          parameters.get(
            "tossdata"
          ) ||
          parameters.get(
            "TOSSDATA"
          ) ||
          "";


        console.log(
          "[PHASE3.4A SILO AJAX TRACE] " +
          JSON.stringify({
            targetDate,
            command,
            tossdata
          })
        );

      } catch (
        traceError
      ) {
        console.warn(
          "[PHASE3.4A SILO AJAX TRACE] listener error:",
          traceError instanceof
            Error
            ? traceError.message
            : traceError
        );
      }
    };


  page.on(
    "request",
    phase34RequestListener
  );


  try {
    console.log(
      "[PHASE3.4A SILO TIMING] start " +
      targetDate
    );


    const capturedValues = {};


    for (
      const definition of
      OIS_SILO_LEVEL_DEFINITIONS
    ) {
      const phase34TagStartedAt =
        Date.now();


      console.log(
        "[PHASE3.4A SILO TIMING] tag start " +
        definition.tag
      );


      let frame =
        await openOisTagLogLookup(
          page
        );


      console.log(
        "[PHASE3.4A SILO TIMING] lookup ready " +
        definition.tag +
        " " +
        (
          (
            Date.now() -
            phase34TagStartedAt
          ) /
          1000
        ).toFixed(
          2
        ) +
        "s"
      );


      await setOisTagLogSearchConditions(
        frame,
        definition.tag,
        targetDate
      );


      console.log(
        "[PHASE3.4A SILO TIMING] conditions ready " +
        definition.tag +
        " " +
        (
          (
            Date.now() -
            phase34TagStartedAt
          ) /
          1000
        ).toFixed(
          2
        ) +
        "s"
      );


      await page.waitForTimeout(
        200
      );


      frame =
        await findOisTagLogFrame(
          page,
          3000
        ) ||
        frame;


      const capturedValue =
        await captureOisTagLog24HourValueFromApi(
          page,
          definition.tag,
          targetDate,

          async () => {
            await clickOisLogSheetSearchButton(
              frame
            );
          }
        );


      console.log(
        "[PHASE3.4A SILO TIMING] tag complete " +
        definition.tag +
        " " +
        (
          (
            Date.now() -
            phase34TagStartedAt
          ) /
          1000
        ).toFixed(
          2
        ) +
        "s"
      );


      capturedValues[
        definition.resultKey
      ] = {
        ...capturedValue,

        label:
          definition.label
      };
    }


    console.log(
      "[PHASE3.4A SILO TIMING] all tags complete " +
      (
        (
          Date.now() -
          phase34SiloStartedAt
        ) /
        1000
      ).toFixed(
        2
      ) +
      "s"
    );


    const result = {
      source:
        "OIS TAG별 LOG 조회",

      targetDate,

      valueColumn:
        "24시",

      flyAshSiloLevel:
        capturedValues
          .flyAsh
          .value,

      bioStorageSiloLevel:
        capturedValues
          .bioStorage
          .value,

      flyAshTag:
        capturedValues
          .flyAsh
          .tag,

      bioStorageTag:
        capturedValues
          .bioStorage
          .tag,

      flyAshItemName:
        capturedValues
          .flyAsh
          .itemName,

      bioStorageItemName:
        capturedValues
          .bioStorage
          .itemName,

      flyAshUnit:
        capturedValues
          .flyAsh
          .unit,

      bioStorageUnit:
        capturedValues
          .bioStorage
          .unit,

      flyAshValueField:
        capturedValues
          .flyAsh
          .valueField,

      bioStorageValueField:
        capturedValues
          .bioStorage
          .valueField,

      collectedAt:
        new Date()
          .toISOString()
    };


    console.log(
      [
        "OIS Silo Level 조회 완료",

        targetDate,

        `Fly Ash ${result.flyAshSiloLevel}${result.flyAshUnit || ""}`,

        `Bio Storage ${result.bioStorageSiloLevel}${result.bioStorageUnit || ""}`
      ].join(
        " · "
      )
    );


    return result;

  } finally {
    page.off(
      "request",
      phase34RequestListener
    );
  }
}


'@

  $Text =
    Replace-Range `
      -Text $Text `
      -Start $FunctionStart `
      -End $FunctionEnd `
      -Replacement $NewFunction

  [IO.File]::WriteAllText(
    $Agent,
    $Text,
    (New-Object Text.UTF8Encoding($false))
  )

  Write-Host ''
  Write-Host '===== Node syntax check ====='

  & $Node --check $Agent

  if ($LASTEXITCODE -ne 0) {
    throw 'Node syntax check failed after patch.'
  }

  Write-Host ''
  Write-Host '===== git diff --check ====='

  git diff --check -- `
    local-tools/ois-agent/ois-login.js

  if ($LASTEXITCODE -ne 0) {
    throw 'git diff --check failed.'
  }

  $Final =
    [IO.File]::ReadAllText($Agent)

  $Checks =
    [ordered]@{
      'Phase 3.4A trace' =
        $Final.Contains(
          '[PHASE3.4A SILO AJAX TRACE]'
        )

      'Phase 3.4A timing' =
        $Final.Contains(
          '[PHASE3.4A SILO TIMING]'
        )

      'Phase 3.3B kept' =
        $Final.Contains(
          '[PHASE3.3B NONBLOCKING STARTUP]'
        )

      'Phase 3.3A kept' =
        $Final.Contains(
          '[PHASE3.3A EXCEL BULK READ]'
        )

      'Phase 3.2 kept' =
        $Final.Contains(
          '[PHASE3.2 WATER DIRECT]'
        )
    }

  Write-Host ''
  Write-Host '===== Verification ====='

  foreach ($Entry in $Checks.GetEnumerator()) {
    Write-Host (
      $Entry.Key +
      ': ' +
      $Entry.Value
    )
  }

  if (
    $Checks.Values -contains
      $false
  ) {
    throw 'Verification failed.'
  }

  Write-Host ''
  Write-Host '===== Diff summary ====='

  git diff --stat -- `
    local-tools/ois-agent/ois-login.js

  Write-Host ''
  Write-Host '===== Phase 3.4A v2 patch complete ====='
  Write-Host 'Silo request behavior is unchanged.'
  Write-Host 'Only request trace and timing logs were added.'
  Write-Host 'Agent has NOT been restarted.'
  Write-Host 'Nothing has been staged or committed.'
}
catch {
  Write-Host ''
  Write-Host '===== Patch failed; restoring Agent ====='

  Copy-Item `
    -LiteralPath $Backup `
    -Destination $Agent `
    -Force

  Write-Host 'Restore complete.'
  throw
}
